import 'bootstrap/dist/css/bootstrap.min.css';
import type { Metadata } from "next";
import {Inter} from 'next/font/google'
import { ThemeProvider } from "@/components/theme-provider"
import Header from "@/components/ui/header";
import { Toaster } from "@/components/ui/toaster"
import "./globals.css";

const inter = Inter({subsets: ['vietnamese']})
export const metadata: Metadata = {
  title: "Home page",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className}`}
      >
        <Toaster />
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
            {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
