import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: {
        template: "Admin | %s",
        default: "Admin",
    },
    description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
    return (
        <SidebarProvider className="setHeight--">
            <AppSidebar />
            <div className="w-full mt-[62px]">
                <SidebarTrigger />
                {children}
            </div>
        </SidebarProvider>
    );
}
